version: "2"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes: 
      - ./client:/client
    depends_on:
      - server
  apidoc:
    build: ./apidoc
    ports: 
      - "5000:5000"
    volumes:
      - ./apidoc:/apidoc
  server: 
    build: ./
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./:/hawkeye